### ISSUE TITLE
Could not get any sources (404)

### ISSUE THREAD

**Issue by darkBuddha** [alleveenstra/mapproxy-mapnik#1]
Hi, 

i am using Ubuntu 18.04 and _think_ i did everything correctly, but when i start the container, it can not load any tiles: [My server](http://159.89.1.160/mapproxy/demo/?srs=EPSG%3A900913&format=image%2Fjpeg&wms_layer=my_layer)

in the pg_hba.conf all sources are set to "trust".

Could it be because i only imported one country and the location of this demo is somewhere else?

I tried to use the server as tileserver for a local leaflet map that loads a location in the country i imported, but it could not load anything too.

What could have gone wrong?

I had to set a password on this step: `sudo -u postgres createuser gis -s`, so i added the parameter "-P".  Otherwise it complained that no password was sent.

I used a newer version of osm2pgsql (0.96) which was a little speedier.

Filling the DB was successful, but had to use the parameter -W here (opens a password prompt).

Could this be the reason? That i set a password and the container does not know anything about it? But shouldn't it be passwordless access anyway through the trust setting in pg_hba.conf?

**Comment by alleveenstra** [comment]
Hi railsGod,

Nice to see this project is used by others!

To help you debug this problem, could you tell me the kind of error you get for a tile from mapnik , for example http://159.89.1.160/osm_tiles/0/0/0.png
And could you see what's in the Apache error logs for this request? 
And can you verify if you can make a connection to your database from the container? psql -h database -u gis

Kind regards,

Alle

**Comment by railsGod** [comment]
Hi, nice to see that this project is still alive! I have to add that am relatively new to docker. The instance is still running (detached) since before my first post. 

When in log into it with `exec -it /bin/bash`, it does not even find psql: `bash: psql command not found`. `top` shows apache2 and renderd running.

**Comment by railsGod** [comment]
`/var/log/apache2/access.log` is completely empty, see `/var/log/apache2/error.log` attached: 
![docker_err1](https://user-images.githubusercontent.com/3326929/40164940-28ba43b2-59bb-11e8-809e-86c349064d32.png)
![docker_err2](https://user-images.githubusercontent.com/3326929/40164941-28dfd730-59bb-11e8-9896-efc3f0c15106.png)
![docker_err3](https://user-images.githubusercontent.com/3326929/40164942-28fdef0e-59bb-11e8-8bfe-88e40a1afff1.png)
![docker_err4](https://user-images.githubusercontent.com/3326929/40164943-29227e1e-59bb-11e8-854e-f22046371a5d.png)
![docker_err5](https://user-images.githubusercontent.com/3326929/40164946-297058aa-59bb-11e8-8ae5-975792fd18f8.png)
![docker_err6](https://user-images.githubusercontent.com/3326929/40164948-298f304a-59bb-11e8-97a3-733ef3bd33c2.png)
![docker_err7](https://user-images.githubusercontent.com/3326929/40164949-29aadbc4-59bb-11e8-8183-1ab82b3d0881.png)

I am trying to set it up myself now, but it would be nice to be able to use this container though. Thanks for any help, very appreciated.

**Comment by railsGod** [comment]
I now shut down the container and try to set up all the components myself. If i can assist you in any way, please let me know.
